title: Dayda
name: City of Sioux Falls
description: >-
  This is a catalog of datasets organized and made more accessible from the City
  of Sioux Falls, SD, providing simple dowloadable CSV and JSON files, as well
  as Postman Collections you can use as part of workflows and other automation.
about: This is all about the entity.
source_url: 'http://example.com'
source_contact_type: general
source_phone: +1 555-555-5555
source_email: info@example.com
source_catalog: data.gov
profile_pic: >-
  http://www.siouxfalls.org/-/media/profile_pics/Logos/City_SF_logo.ashx?h=87&la=en&w=304&hash=E6D8A542D64FD4A87277F2EAB524933FAB586EF1
favicon: /assets/img/favicon.png
url: 'http://city-of-sioux-falls.dayda.org'
encoding: utf-8
paginate: 25
paginate_path: '/page:num/'
markdown: kramdown
